title: Elbsides

author:
  name: elbsides -at- gmail.com


# logo: /assets/images/elbsides_logo.svg
# email: elbsides -at- gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the home of Elbsides, Hamburg's premier security community driven security conference.
# baseurl: "/www" # the subpath of your site, e.g. /blog
url: "https://www.elbsides.eu/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: elbsides
# mastodon_username: elbsides

# Build settings
theme: minima
# plugins:
  # - jekyll-feed
  # - jekyll-seo-tagx

#markdown: kramdown
#highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# minima:
social_links:
  -
    platform: linkedin
    title: linkedin.com/company/elbsides
    user_url: "https://www.linkedin.com/company/elbsides/?viewAsMember=true"
  -
    platform: x
    title: "@elbsides"
    user_url: "https://twitter.com/elbsides"
  -
    platform: youtube
    user_url: "https://www.youtube.com/@elbsides78"
  -
    platform: mastodon
    user_url: "https://infosec.exchange/@elbsides"
